FROM ubuntu 
WORKDIR /pepe
COPY blankLinesCounter.sh .
COPY findNames.sh .
COPY menu.sh .
COPY statsSentences.sh .
COPY statsUsageWords.sh .
COPY statsWords.sh .
COPY caseConverter.sh .
COPY substringReplace.sh .
COPY blockSelection.sh .
COPY palindromeDetection.sh .
COPY texto_pagina .
CMD ["bash","./menu.sh"]
